### PR TITLE
Eliminating dependence on jquery

### PR DESCRIPTION
**Pull request by Jorgevillada**

### CODE REVIEW

**Comment by mwasiluk** [comment]
There are some issues with sorting inside elements in your version (Chrome, FF, Edge). Please fix them and then I'll merge your pull request. Thanks!

**Comment by Jorgevillada** [comment]
You could tell me if the error persists. or if you find more? Thank you

**Comment by mwasiluk** [comment]
It seems to work well in viewer, but there are still issues with ordering available items/options in questions builder, eg in:
src/builder/question-offered-answer-list-builder.directive.js
src/builder/question-division-builder.directive.js
src/builder/question-grid-builder.directive.js

In src/builder/question-priority-list-builder.directive.js ordering still works strange, eg try dragging first item to last position.

**Comment by Jorgevillada** [comment]
waiting for next release for strange behavior in question-priority-list-builder.directive PR(https://github.com/RubaXa/Sortable/pull/624) when used drag-handle.

**Pull request merged**
